[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "invalid-name",
    "import-error",
    "redefined-outer-name",
    "missing-timeout"
]
